<?php
$user='root';
$pass='';
$db='db_srm_lib';
$conn=mysqli_connect('localhost',$user,$pass,$db)or die("Unable to connect");
if(isset($_POST['name']))
{
$name=$_POST['name'];
}
if(isset($_POST['age']))
{
$age=$_POST['age'];
}
if(isset($_POST['mobile']))
{
$ph=$_POST['mobile'];
}
if(isset($_POST['mail']))
{
$email=$_POST['mail'];
}
if(isset($_POST['pass']))
{
$passw=$_POST['pass'];
}
if(isset($_POST['repass']))
{
$rpass=$_POST['repass'];
}
$sql="INSERT INTO bsignup (Name,Age,Mobile,Email,Password,Repass) VALUES ('$name','$age','$ph','$email','$passw','$rpass')";
if(mysqli_query($conn,$sql))
{
header("Location:signedup.html");
}
else
{
echo"ERROR";
}
?>